### ISSUE TITLE
Setup instructions for a variant Github App

### ISSUE THREAD

**Issue by jywarren** [hoodiehq/first-timers-bot#166]
Hi, we've forked and made a small tweak to the workflow to match the Public Lab process, where we don't do an invitation and assignment before asking for a PR -- we try to just encourage people to submit a PR as early as possible to start a discussion about the contribution. 

We love your setup and your bot, we just have a different checklist so we'd like to register a "variant" app based on our fork: https://github.com/publiclab/first-timers-bot/blob/master/instructions.md

I'm not sure what to use as the `Webhook URL` or `Webhook secret` when creating a new GitHub app at https://github.com/organizations/publiclab/settings/apps/new. Can you advise? Thank you for this wonderful project!

**Comment by agonzalez0515** [comment]
Hi @jywarren! Thank you for using our bot and for the compliment. We implemented the ability for you to use your own instructions.md file without having to redeploy the bot! Check out the Configuration section of our [README](https://github.com/hoodiehq/first-timers-bot#configuration). You can add a markdown file to the .github folder and the bot will use that template instead of the one we have :sunglasses: . We listed a project currently using this setup in the README if you would like to see an example. Let us know if you have any questions or problems with this feature.

**Comment by gr2m** [comment]
Hello Jeffrey, hope things are well :)

As Angie mentioned, the template is fully configurable :)

I had a thought about the current default instructions myself lately. The current instructions are based on what we do at Hoodie: https://github.com/hoodiehq/camp/blob/gh-pages/.github/ISSUE_TEMPLATE.md

Inviting people as collaborators is a workflow that worked for Hoodie’s dedicated "camp" repository, but other projects don’t seem follow that. It's nice when folks can check off the checklist which they only can do once they have write access to the repository, but I agree that is often times not possible due to security concerns.

Besides that, I was thinking about the scalability of these first-timers-only issues. I think it would be nice to have multiple people submit a pull request, even if only one gets merged. I’ve started experimenting with this approach, e.g. see https://github.com/hoodiehq/camp/issues/132#issuecomment-338427967

I think this works great and people appreciate it _so much_ that they can just send a pull request, even if it doesn’t get merged :) So I was thinking, maybe we should remove the checklist altogether and make the default template say that everyone is welcome to send a pull request to practise, but that only one can get merged, which will be chosen by random. Something in that direction?

Sorry to hijack the issue Jeffrey, I’d just love to hear your thoughts as an outside user of First Timers :)

**Comment by jywarren** [comment]
Hi, very cool to hear of this, and we're doing a lot of experimentation ourselves on newcomer engagement. 

Ah!!! A markdown file to the `.github` directory of MY project? That makes a LOT of sense and is really cool. Do you think I could file a PR to amend the docs to make that extra clear? I missed it first time around.

**Comment by jywarren** [comment]
Our preference is not entirely based on security, by the way -- just as a matter of how many back-and-forths are required to start working, we like to do periodic batch invitations to all new contributors, rather than having them wait before making their contribution. But it's super cool to hear all the ways you're thinking about this. 

I'm trying to put together a talk for LibrePlanet to recap a lot of the different strategies we've learned and prototyped ourselves, including some from Hoodie. Also been very interested in "reusable" `first-timers-only` issues -- even ones where multiple PR merges are possible (a 'repeating' task). We've even thought of maintaining a single "keeps-on-giving" issue which asks for something useful, though something that is never really completed. Maybe... updating the contributors file? Too meta? :-)

**Comment by jywarren** [comment]
Maybe there should be like an "OnboardingCon" or "Welcoming Summit"... are there events like that you're familiar with, for swapping strategies for this stuff?

**Comment by jywarren** [comment]
OK - doing this here: https://github.com/publiclab/plots2/pull/1720

Thanks!!!

**Comment by gr2m** [comment]
note that something’s funky with what should be emoji I think?
https://github.com/jywarren/plots2/blob/77d701790d173e6ef397cdd644092d965cd011ee/.github/first-timers-issue-template.md

**Comment by jywarren** [comment]
egads! good catch!

**Comment by jywarren** [comment]
Hi, @gr2m and @agonzalez0515 -- also, we're starting to think about a mini-survey to assess our outreach efforts. If you've done anything like this, or are interested in it, we'd love to chat!

https://publiclab.org/notes/warren/10-25-2017/help-with-a-standard-mini-evaluation-for-assessing-software-outreach-efforts

**Comment by gr2m** [comment]
This looks great, I'd love to chat myself. One thing I'm mostly interested in is scaleability of contributor onboarding and contributor retention :)
