### ISSUE TITLE
Issue template mangled if diff contains code block

### ISSUE THREAD

**Issue by pathawks** [hoodiehq/first-timers-bot#174]
If a diff contains a triple-backtick code block, the created issue becomes mangled when it tries to include this in the displayed diff (see below).

I guess the backticks need to be escaped somehow, but I'm not sure how to do that in this context. HTML entity displays literally. Backslash displays literally.

---

<img width="691" alt="screen shot 2017-11-10 at 5 25 01 pm" src="https://user-images.githubusercontent.com/251545/32682749-5f37f604-c63c-11e7-89fd-338e8a3827dc.png">

**Comment by gr2m** [comment]
I’ve run into this problem myself, but I think I found a workaround! Turns out we can use more than 3 backticks to wrap a code block, that way it will show all backticks until it finds the same amount again. Here is an example, I wrapped it in 7 backticks :D

````````
```````diff
-testing 1
+```
+funky
+```
+testing 2
```````
````````

The image of the code for reference

<img width="99" alt="image" src="https://user-images.githubusercontent.com/39992/32995784-4090def2-cd2e-11e7-86a9-dda6f0bc00da.png">

So I think what we can do is to use 4 backticks instead of 3. Could you give this a try, maybe send a pull request? 🙏

**Comment by pathawks** [comment]
I didn't know this about GitHub Flavored MarkDown! This is pretty cool!
